### ISSUE TITLE
「Tracker」三方地图接入架构升级

### ISSUE THREAD

**Issue by lvisei** [antvis/L7#2411]
## 背景

1. 数据流程中存在[特殊底图](https://github.com/antvis/L7/blob/56d800f06319d54556b4dc36303d893a6f8738d4/packages/layers/src/plugins/DataMappingPlugin.ts#L170-L174)高耦合逻辑（高德 V2 / 平面 [SIMPLE](https://l7.antv.antgroup.com/examples/point/text/#simplecoordinate) 投影模式），数据流程中存在多种情形，阅读晦涩，难以维护
2. 三方地图接入模式不统一，多种模式，高德的接入对 L7 是侵入式的修改
3. L7 坐标系统复杂，shader 8 种坐标系统，偏移坐标有 4 种（LNGLAT_OFFSET、P20_OFFSET、METER_OFFSET、P20_2）

### 三方地图接入升级为统一的视口同步

- [ ] 高德 V2 地图接入升级为统一的视口同步
- [ ] 百度、腾讯、谷歌、天地图、Mapbox 基于抽象类 BaseMap 实现各自方法，补全缺失方法、解决类型问题

### 数据抖动升级（大于 20 级时）

- [ ] 使用偏移坐标时，shader 里投影方案升级验证

### 非地理坐标投影升级

- [ ] SIMPLE 模式升级为直投影， shader 里支持平面投影模式

### 旧版地图方案移除

- [ ] 高德 V1  Map 移除，删除内置坐标系 P20 和 P20_OFFSET，删除 shader 里的[投影逻辑](https://github.com/antvis/L7/blob/fd086021e5dad29c453fc49a698da88bc5f6fc98/packages/core/src/shaders/projection.glsl#L103-L109)
- [ ] 高德 V2 旧方案 Map 移除，删除内置坐标系 P20_2，删除数据流流程植入逻辑、shader 里的投影逻辑

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lvisei** [comment]
数据抖动升级后，shader 修改待来的弧线纹理贴图问题

<table>
<tr>
 <td>
before
 <td>
now
<tr>
 <td>

<img width="889" alt="image" src="https://github.com/antvis/L7/assets/26923747/927fe05a-a414-41ab-8f92-ad543cbc5fd7">

 <td>

![image](https://github.com/antvis/L7/assets/26923747/970394f7-5cd6-40d0-a1b9-507099b947fa)

</table>

**Comment by lvisei** [comment]
### 三方地图拆封到插件

- [ ] 百度、腾讯、谷歌、天地图、Mapbox 基于抽象类 BaseMap 实现各自方法，补全缺失方法、解决类型问题
- [ ] 一方 Map 升级，同步升级到 Maplibre 最新版
- [ ] https://github.com/antvis/L7/issues/2487
